### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by raphaelbs** [dai-shi/excalidraw-claymate#9]
After using it for some diagrams, I felt the need to have some additional features which I'm happy to investigate and implement by myself.
But first, I want to discuss if it makes sense and get inputs about it. The list is sorted by priority.

- [ ] To add E2E tests with Cypress to prevent bugs while working on improvements. We can discuss what are the relevant test cases on a separate issue;
- [ ] To add a global delay between all frames; (#1)
- [ ] The ability to export with a different format e.g. MP4, reveal.js, impress.js, or something else that contains presentation controls;
- [ ] To add an automatic variable delay between frames considering the amount of text included on the frame. Something like https://niram.org/read/;
- [ ] To add a click-to-edit (preferable) or a click-to-zoom feature at the snapshots; 
- [ ] Preview animated gif; (#3) 
- [ ] To add a toggle on the preview bar;

**Comment by dai-shi** [comment]
Oh, that's super nice! I'm happy to help you. There should be something I could learn, which is a nice thing.
I don't go each item in the list into detail now. Why won't you create new issues for all missing items, then we can discuss separately?

I have one thing to add: Currently, the snapshot size is determined by the first shot. This is very counter-intuitive. We should have a clearer way to show the snapshot region.

**Comment by raphaelbs** [comment]
> Why won't you create new issues for all missing items
Sure!

> Currently, the snapshot size is determined by the first shot. This is very counter-intuitive. We should have a clearer way to show the snapshot region.

Yeah. I even found a bug related to this. For some reason, the initial aspect ratio is being persisted even after removing the first frame:

<details>
<summary>Click to see the video</summary>

https://user-images.githubusercontent.com/11169832/111246285-ba536f80-85e4-11eb-90e3-8b497fed8563.mp4

</details>

I still don't have a good idea of how to manipulate or display the region though.

**Comment by dai-shi** [comment]
https://twitter.com/Vjeux/status/1371661558502150144
UI-wise, this looks close to what we want to do.

By the way, do you have a discord account? https://discord.gg/MrQdmzd

**Comment by dai-shi** [comment]
> The ability to export with a different format

Would be nice to export to SVG with/without animation.
[excalidraw-animate](https://github.com/dai-shi/excalidraw-animate) is for automatic animation, but claymate is more for manual animation.

**Comment by dai-shi** [comment]
ref: https://twitter.com/fortysevenfx/status/1387688076835762176
We'd like to make each snapshot editable like https://github.com/scastiel/excalidraw-slides.
(implementation memo: store data instead of canvas.)
